name: truck_backer_upper
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libcxx=20.1.3
  - libffi=3.4.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.0.1
  - python=3.12.8
  - readline=8.2
  - setuptools=79.0.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.2
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - graphviz==0.20.3
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.5
      - packaging==25.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - protobuf==6.30.2
      - psutil==7.0.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.15.2
      - sentry-sdk==2.26.1
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - torch==2.6.0
      - torchviz==0.0.3
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - wandb==0.19.10
